import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  name = 'Angular';
  posts=[
    {title:"1st", content:"1st content"},
    {title:"2nd", content:"2nd content"},
    {title:"3rd", content:"3rd content"}
  ]
  ttt= this.posts.length - 2 ;

  addr = {
   "pageIndex":1,
   "pageSize":18,
   "totalPages":15,
   "totalCount":254,
   "items":[
      {
         "basicInfo":{
            "id":551,
            "unitId":"82dd715be7047c85",
            "status":"InspectionPending",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":false,
            "publishedOn":"2019-08-20T06:06:19.6040555+00:00",
            "onboardingInfo":{
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "ExteriorPhotos",
               "RoomsPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2019-08-06T00:26:51.3370559+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/492-551-48012f7023568b3a",
            "detailBasic":{
               "unitType":"None",
               "unitLevel":"None",
               "floors":1
            },
            "address":{
               "addressId":"f54d53b8b187531a",
               "streetAddress":"161 Columbia Avenue",
               "city":"Redwood City",
               "zipcode":"94063",
               "state":"CA",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.20805940000002",
                  "longitude":"37.4698725"
               }
            },
            "unitNumber":"",
            "areaInSquareFeet":1030,
            "bedroomCount":2,
            "fullBathroomCount":1,
            "halfBathroomCount":0,
            "yearBuilt":1940,
            "zillowListingId":"3z3de4jptv27t_Postlets"
         },
         "address":{
            "addressId":"f54d53b8b187531a",
            "streetAddress":"161 Columbia Avenue",
            "city":"Redwood City",
            "zipcode":"94063",
            "state":"CA",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.20805940000002",
               "longitude":"37.4698725"
            }
         },
         "listingInfo":{
            "depositAmount":3450.0000,
            "rentAmount":3450.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":874,
            "unitId":"128a71b211a1d19a",
            "status":"InspectionCompleted",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":true,
            "publishedOn":"2020-02-29T05:53:19.3327512+00:00",
            "onboardingInfo":{
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "RoomsPhotos",
               "ExteriorPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2019-10-16T21:40:55.3889712+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/800-874-8b40273ea5b8fc35",
            "detailBasic":{

            },
            "address":{
               "addressId":"ddc18cf4507315e1",
               "streetAddress":"680 23rd Street",
               "city":"Oakland",
               "zipcode":"94612",
               "state":"CA",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.273552",
                  "longitude":"37.813967"
               }
            },
            "unitNumber":"",
            "areaInSquareFeet":1600,
            "bedroomCount":4,
            "fullBathroomCount":1,
            "halfBathroomCount":0,
            "zillowListingId":"18071j5jwn9bm_Postlets"
         },
         "address":{
            "addressId":"ddc18cf4507315e1",
            "streetAddress":"680 23rd Street",
            "city":"Oakland",
            "zipcode":"94612",
            "state":"CA",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.273552",
               "longitude":"37.813967"
            }
         },
         "listingInfo":{
            "depositAmount":3000.0000,
            "rentAmount":3000.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1031,
            "unitId":"f68e2a1e8942346b",
            "status":"InspectionScheduled",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":false,
            "publishedOn":"2019-11-26T07:56:03.5752449+00:00",
            "onboardingInfo":{

            },
            "mediaAvailable":[
               "ExteriorPhotos",
               "RoomsPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2019-11-18T21:18:50.5591763+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/927-1031-e3c36a37312c382",
            "address":{
               "addressId":"d2f8266e35e134b6",
               "streetAddress":"7442 Hillmont Drive",
               "city":"Oakland",
               "zipcode":"94605",
               "state":"CA",
               "unitNumber":"B",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.16770880000001",
                  "longitude":"37.7709373"
               }
            },
            "unitNumber":"B",
            "areaInSquareFeet":600,
            "bedroomCount":1,
            "fullBathroomCount":1,
            "halfBathroomCount":0,
            "yearBuilt":1958,
            "zillowListingId":"2aw69c4eyb3rs_Postlets"
         },
         "address":{
            "addressId":"d2f8266e35e134b6",
            "streetAddress":"7442 Hillmont Drive",
            "city":"Oakland",
            "zipcode":"94605",
            "state":"CA",
            "unitNumber":"B",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.16770880000001",
               "longitude":"37.7709373"
            }
         },
         "listingInfo":{
            "depositAmount":2200.0000,
            "rentAmount":2200.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1123,
            "unitId":"d39ea82656b26b3d",
            "status":"InspectionScheduled",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":false,
            "publishedOn":"2020-04-06T10:59:36.2045313+00:00",
            "onboardingInfo":{
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "ExteriorPhotos",
               "RoomsPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2019-12-10T15:57:24.4795421+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/1004-1123-a03f9c122d560717",
            "detailBasic":{
               "unitType":"None",
               "unitLevel":"None"
            },
            "address":{
               "addressId":"1cedd183995c317d",
               "streetAddress":"100 Bradford Street",
               "city":"San Francisco",
               "zipcode":"94110",
               "state":"CA",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.40972729999999",
                  "longitude":"37.74124279999999"
               }
            },
            "unitNumber":"",
            "areaInSquareFeet":1250,
            "bedroomCount":3,
            "fullBathroomCount":2,
            "halfBathroomCount":0,
            "yearBuilt":1965,
            "zillowListingId":"2g6udy20q22cx_Postlets"
         },
         "address":{
            "addressId":"1cedd183995c317d",
            "streetAddress":"100 Bradford Street",
            "city":"San Francisco",
            "zipcode":"94110",
            "state":"CA",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.40972729999999",
               "longitude":"37.74124279999999"
            }
         },
         "listingInfo":{
            "depositAmount":5100.0000,
            "rentAmount":5100.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1310,
            "unitId":"bad757c92eb7580b",
            "status":"InspectionCompleted",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":true,
            "publishedOn":"2020-01-21T08:48:22.6348086+00:00",
            "onboardingInfo":{
               "condition":"ShinyPalace",
               "rentalStatus":"OwnerOccupied",
               "moveoutOn":"2030-02-01T08:00:00Z",
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "RoomsPhotos",
               "ExteriorPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2020-01-17T21:50:13.1588934+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/1179-1310-32ea69f439251dff",
            "detailBasic":{
               "floors":3
            },
            "address":{
               "addressId":"7b7cc31115e6f323",
               "streetAddress":"2219 Curtis Street",
               "city":"Oakland",
               "zipcode":"94607",
               "state":"CA",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.2772766",
                  "longitude":"37.813797"
               }
            },
            "unitNumber":"",
            "areaInSquareFeet":1542,
            "bedroomCount":3,
            "fullBathroomCount":2,
            "halfBathroomCount":1,
            "zillowListingId":"58qrnwec90kwa_Postlets"
         },
         "address":{
            "addressId":"7b7cc31115e6f323",
            "streetAddress":"2219 Curtis Street",
            "city":"Oakland",
            "zipcode":"94607",
            "state":"CA",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.2772766",
               "longitude":"37.813797"
            }
         },
         "listingInfo":{
            "depositAmount":4650.0000,
            "rentAmount":4650.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1528,
            "unitId":"17efedad8e85934",
            "status":"InspectionCompleted",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":true,
            "publishedOn":"2020-03-26T10:20:12.81455+00:00",
            "onboardingInfo":{
               "condition":"ShinyPalace",
               "rentalStatus":"Vacant",
               "availableForRentOn":"2020-02-24T00:00:00",
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "ExteriorPhotos",
               "RoomsPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2020-02-21T20:09:47.2922032+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/1367-1528-67706d77b3aea201",
            "detailBasic":{
               "unitType":"Studio",
               "unitLevel":"None",
               "floors":1
            },
            "address":{
               "addressId":"23f43ae4ca448ad4",
               "streetAddress":"574 Natoma Street",
               "city":"San Francisco",
               "zipcode":"94103",
               "state":"CA",
               "unitNumber":"402",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.4094507",
                  "longitude":"37.7790184"
               }
            },
            "unitNumber":"402",
            "areaInSquareFeet":370,
            "bedroomCount":1,
            "fullBathroomCount":1,
            "halfBathroomCount":0
         },
         "address":{
            "addressId":"23f43ae4ca448ad4",
            "streetAddress":"574 Natoma Street",
            "city":"San Francisco",
            "zipcode":"94103",
            "state":"CA",
            "unitNumber":"402",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.4094507",
               "longitude":"37.7790184"
            }
         },
         "listingInfo":{
            "depositAmount":2650.0000,
            "rentAmount":2650.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":97,
            "unitId":"7f017eaa0a4c595b",
            "status":"InspectionScheduled",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":false,
            "onboardingInfo":{
               "condition":"ShinyPalace",
               "rentalStatus":"RenterOccupied",
               "currentLeaseEndOn":"2019-12-01T08:00:00+00:00",
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "ExteriorPhotos",
               "RoomsPhotos",
               "Matterport",
               "Map",
               "GuidedTour"
            ],
            "managedSince":"2019-01-24T04:27:09.1209033+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/49-97-13080fdd027e1eb0",
            "detailBasic":{
               "unitType":"None",
               "unitLevel":"None",
               "floors":1
            },
            "address":{
               "addressId":"6f65ad6abd2607bc",
               "streetAddress":"1905 West Street",
               "city":"Oakland",
               "zipcode":"94612",
               "state":"CA",
               "unitNumber":"C",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.27763800000002",
                  "longitude":"37.811114"
               }
            },
            "unitNumber":"C",
            "areaInSquareFeet":833,
            "bedroomCount":2,
            "fullBathroomCount":1,
            "halfBathroomCount":0,
            "yearBuilt":1901,
            "zillowListingId":"1dfq2k29k1746_Postlets"
         },
         "address":{
            "addressId":"6f65ad6abd2607bc",
            "streetAddress":"1905 West Street",
            "city":"Oakland",
            "zipcode":"94612",
            "state":"CA",
            "unitNumber":"C",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.27763800000002",
               "longitude":"37.811114"
            }
         },
         "listingInfo":{
            "depositAmount":2300.0000,
            "rentAmount":2300.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":119,
            "unitId":"5e83945d69254b13",
            "status":"InspectionScheduled",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":false,
            "publishedOn":"2020-02-22T05:49:44.2255371+00:00",
            "onboardingInfo":{
               "condition":"ShinyPalace",
               "rentalStatus":"OwnerOccupied",
               "moveoutOn":"2020-01-01T08:00:00Z",
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "ExteriorPhotos",
               "RoomsPhotos",
               "Matterport",
               "Map",
               "GuidedTour"
            ],
            "managedSince":"2019-02-20T07:42:51.1241005+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/95-119-1fc8a40900993051",
            "detailBasic":{
               "floors":1
            },
            "address":{
               "addressId":"9d1e49bef4ddceaf",
               "streetAddress":"1075 Market Street",
               "city":"San Francisco",
               "zipcode":"94103",
               "state":"CA",
               "unitNumber":"607",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.41161499999998",
                  "longitude":"37.780644"
               }
            },
            "unitNumber":"607",
            "areaInSquareFeet":500,
            "bedroomCount":1,
            "fullBathroomCount":1,
            "halfBathroomCount":0,
            "zillowListingId":"m6neu0s5fuwc_Postlets"
         },
         "address":{
            "addressId":"9d1e49bef4ddceaf",
            "streetAddress":"1075 Market Street",
            "city":"San Francisco",
            "zipcode":"94103",
            "state":"CA",
            "unitNumber":"607",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.41161499999998",
               "longitude":"37.780644"
            }
         },
         "listingInfo":{
            "depositAmount":2600.0000,
            "rentAmount":2600.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1092,
            "unitId":"30fa9bba821e67a2",
            "status":"InspectionCompleted",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":true,
            "publishedOn":"2020-02-10T12:12:54.0265739+00:00",
            "onboardingInfo":{
               "condition":"ShinyPalace",
               "rentalStatus":"RenterOccupied",
               "currentRentAmount":3370.0,
               "currentLeaseEndOn":"2019-12-01T08:00:00Z",
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "ExteriorPhotos",
               "RoomsPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2019-12-03T04:21:06.2518089+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/973-1092-90dedba14f7d357f",
            "detailBasic":{
               "floors":1
            },
            "address":{
               "addressId":"ef1d7681cad8436d",
               "streetAddress":"1685 Whitwood Lane",
               "city":"Campbell",
               "zipcode":"95008",
               "state":"CA",
               "unitNumber":"4",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-121.97943620000001",
                  "longitude":"37.2846529"
               }
            },
            "unitNumber":"4",
            "areaInSquareFeet":773,
            "bedroomCount":2,
            "fullBathroomCount":1,
            "halfBathroomCount":0,
            "zillowListingId":"3x8udvx0ebb27_Postlets"
         },
         "address":{
            "addressId":"ef1d7681cad8436d",
            "streetAddress":"1685 Whitwood Lane",
            "city":"Campbell",
            "zipcode":"95008",
            "state":"CA",
            "unitNumber":"4",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-121.97943620000001",
               "longitude":"37.2846529"
            }
         },
         "listingInfo":{
            "depositAmount":2800.0000,
            "rentAmount":2800.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1406,
            "unitId":"f465b79b0ffa88e0",
            "status":"InspectionCompleted",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":true,
            "publishedOn":"2020-02-21T00:42:49.4139768+00:00",
            "onboardingInfo":{
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "RoomsPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2020-01-28T20:44:08.638034+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/1260-1406-9ccf73ff52aff1f1",
            "detailBasic":{

            },
            "address":{
               "addressId":"2672ec3944d0d144",
               "streetAddress":"34141 Finnigan Terrace",
               "city":"Fremont",
               "zipcode":"94555",
               "state":"CA",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.0572661",
                  "longitude":"37.5649938"
               }
            },
            "unitNumber":"",
            "areaInSquareFeet":1857,
            "bedroomCount":4,
            "fullBathroomCount":2,
            "halfBathroomCount":1,
            "yearBuilt":1990,
            "zillowListingId":"1n8ddpje2bt6z_Postlets"
         },
         "address":{
            "addressId":"2672ec3944d0d144",
            "streetAddress":"34141 Finnigan Terrace",
            "city":"Fremont",
            "zipcode":"94555",
            "state":"CA",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.0572661",
               "longitude":"37.5649938"
            }
         },
         "listingInfo":{
            "depositAmount":4050.0000,
            "rentAmount":4050.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1550,
            "unitId":"747ef8f3747bab3d",
            "status":"InspectionCompleted",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":true,
            "publishedOn":"2020-03-07T03:46:03.4386011+00:00",
            "onboardingInfo":{
               "condition":"ShinyPalace",
               "rentalStatus":"Vacant",
               "availableForRentOn":"2020-02-25T00:00:00",
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "RoomsPhotos",
               "ExteriorPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2020-02-25T21:33:47.8113413+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/1388-1550-43d655094cdc898b",
            "detailBasic":{
               "unitType":"None",
               "unitLevel":"Ground Level",
               "floors":1
            },
            "address":{
               "addressId":"83af64d2fb601907",
               "streetAddress":"49 Oak Avenue",
               "city":"Redwood City",
               "zipcode":"94061",
               "state":"CA",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.2238851",
                  "longitude":"37.4765865"
               }
            },
            "unitNumber":"",
            "areaInSquareFeet":1200,
            "bedroomCount":3,
            "fullBathroomCount":2,
            "halfBathroomCount":0,
            "zillowListingId":"3pxwp7h39323b_Postlets"
         },
         "address":{
            "addressId":"83af64d2fb601907",
            "streetAddress":"49 Oak Avenue",
            "city":"Redwood City",
            "zipcode":"94061",
            "state":"CA",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.2238851",
               "longitude":"37.4765865"
            }
         },
         "listingInfo":{
            "depositAmount":4950.0000,
            "rentAmount":4950.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1286,
            "unitId":"322daa547a205ada",
            "status":"InspectionCompleted",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":true,
            "publishedOn":"2020-03-16T07:28:12.3245603+00:00",
            "onboardingInfo":{
               "condition":"PrettyGood",
               "rentalStatus":"OwnerOccupied",
               "moveoutOn":"2020-02-01T08:00:00Z",
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "RoomsPhotos",
               "ExteriorPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2020-01-13T23:49:11.6901448+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/1155-1286-d8b5b0e3428cf9e4",
            "detailBasic":{

            },
            "address":{
               "addressId":"40c427e33b9f7a40",
               "streetAddress":"555 Bartlett Street",
               "city":"San Francisco",
               "zipcode":"94110",
               "state":"CA",
               "unitNumber":"303",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.4191095",
                  "longitude":"37.748364"
               }
            },
            "unitNumber":"303",
            "areaInSquareFeet":821,
            "bedroomCount":1,
            "fullBathroomCount":1,
            "halfBathroomCount":0,
            "yearBuilt":2009,
            "zillowListingId":"ayvrgzn97e4d_Postlets"
         },
         "address":{
            "addressId":"40c427e33b9f7a40",
            "streetAddress":"555 Bartlett Street",
            "city":"San Francisco",
            "zipcode":"94110",
            "state":"CA",
            "unitNumber":"303",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.4191095",
               "longitude":"37.748364"
            }
         },
         "listingInfo":{
            "depositAmount":3800.0000,
            "rentAmount":3800.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1497,
            "unitId":"9a85249b2eaa8d12",
            "status":"InspectionCompleted",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":true,
            "publishedOn":"2020-02-14T01:43:07.3442235+00:00",
            "onboardingInfo":{
               "rentalStatus":"Vacant",
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "RoomsPhotos",
               "ExteriorPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2020-02-14T00:06:20.8477331+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/1337-1497-5541a2bea938f0f3",
            "detailBasic":{

            },
            "address":{
               "addressId":"767d6b410869feee",
               "streetAddress":"2220 Santiago Street",
               "city":"San Francisco",
               "zipcode":"94116",
               "state":"CA",
               "unitNumber":"2220",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.491288",
                  "longitude":"37.744484"
               }
            },
            "unitNumber":"2220",
            "areaInSquareFeet":1550,
            "bedroomCount":3,
            "fullBathroomCount":1,
            "halfBathroomCount":0,
            "yearBuilt":1949
         },
         "address":{
            "addressId":"767d6b410869feee",
            "streetAddress":"2220 Santiago Street",
            "city":"San Francisco",
            "zipcode":"94116",
            "state":"CA",
            "unitNumber":"2220",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.491288",
               "longitude":"37.744484"
            }
         },
         "listingInfo":{
            "depositAmount":4099.0000,
            "rentAmount":4099.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1727,
            "unitId":"3b4b16f4273fd9a6",
            "status":"InspectionPending",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":false,
            "publishedOn":"2020-03-30T23:05:41.2644859+00:00",
            "onboardingInfo":{
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "ExteriorPhotos",
               "RoomsPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2020-03-28T04:00:59.3535658+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/1070-1727-efc53ddf25224757",
            "detailBasic":{

            },
            "address":{
               "addressId":"5015e74fbcf37fa7",
               "streetAddress":"662 33rd Street",
               "city":"Richmond",
               "zipcode":"94804",
               "state":"CA",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.3361491",
                  "longitude":"37.9407099"
               }
            },
            "unitNumber":"",
            "areaInSquareFeet":1975,
            "bedroomCount":4,
            "fullBathroomCount":3,
            "halfBathroomCount":0,
            "yearBuilt":1943,
            "zillowListingId":"43znqnndtk8ff_Postlets"
         },
         "address":{
            "addressId":"5015e74fbcf37fa7",
            "streetAddress":"662 33rd Street",
            "city":"Richmond",
            "zipcode":"94804",
            "state":"CA",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.3361491",
               "longitude":"37.9407099"
            }
         },
         "listingInfo":{
            "depositAmount":3800.0000,
            "rentAmount":3800.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1708,
            "unitId":"798f53d83f1e7299",
            "status":"InspectionCompleted",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":true,
            "publishedOn":"2020-03-28T01:26:43.9035426+00:00",
            "onboardingInfo":{
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "ExteriorPhotos",
               "RoomsPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2020-03-23T21:41:00.359382+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/1507-1708-23f65531b0483b07",
            "detailBasic":{
               "unitType":"None",
               "unitLevel":"Penthouse",
               "floors":1
            },
            "address":{
               "addressId":"f1238dfbe2ceed3e",
               "streetAddress":"11801 Avon Way",
               "city":"Los Angeles",
               "zipcode":"90066",
               "state":"CA",
               "unitNumber":"7",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-118.4172915",
                  "longitude":"33.9980676"
               }
            },
            "unitNumber":"7",
            "areaInSquareFeet":2000,
            "bedroomCount":3,
            "fullBathroomCount":3,
            "halfBathroomCount":0,
            "yearBuilt":2006,
            "zillowListingId":"3pvr22t8csa68_Postlets"
         },
         "address":{
            "addressId":"f1238dfbe2ceed3e",
            "streetAddress":"11801 Avon Way",
            "city":"Los Angeles",
            "zipcode":"90066",
            "state":"CA",
            "unitNumber":"7",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-118.4172915",
               "longitude":"33.9980676"
            }
         },
         "listingInfo":{
            "depositAmount":5300.0000,
            "rentAmount":5300.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1562,
            "unitId":"b0530d9374abd8c4",
            "status":"InspectionCompleted",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":true,
            "publishedOn":"2020-03-19T05:47:02.4178497+00:00",
            "onboardingInfo":{
               "condition":"QuiteAverage",
               "rentalStatus":"Vacant",
               "previousRentAmount":2400.0,
               "previousLeaseEndOn":"2019-10-01T07:00:00Z",
               "availableForRentOn":"2020-02-28T00:00:00",
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "RoomsPhotos",
               "ExteriorPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2020-02-27T00:07:59.199243+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/1397-1562-faec7a898692a89d",
            "detailBasic":{
               "unitType":"None",
               "unitLevel":"None",
               "floors":2
            },
            "address":{
               "addressId":"c936ab7ceb450961",
               "streetAddress":"1188 Edsel Drive",
               "city":"Milpitas",
               "zipcode":"95035",
               "state":"CA",
               "unitNumber":"4",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-121.883366",
                  "longitude":"37.4301854"
               }
            },
            "unitNumber":"4",
            "areaInSquareFeet":704,
            "bedroomCount":2,
            "fullBathroomCount":1,
            "halfBathroomCount":0,
            "zillowListingId":"qd01vqz4tnm2_Postlets"
         },
         "address":{
            "addressId":"c936ab7ceb450961",
            "streetAddress":"1188 Edsel Drive",
            "city":"Milpitas",
            "zipcode":"95035",
            "state":"CA",
            "unitNumber":"4",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-121.883366",
               "longitude":"37.4301854"
            }
         },
         "listingInfo":{
            "depositAmount":2300.0000,
            "rentAmount":2300.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1687,
            "unitId":"841a1e3480d1b14a",
            "status":"InspectionCompleted",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":true,
            "publishedOn":"2020-03-23T18:40:11.8277162+00:00",
            "onboardingInfo":{
               "rentalStatus":"Vacant",
               "previousRentAmount":4200.0,
               "previousLeaseEndOn":"2020-01-01T08:00:00Z",
               "availableForRentOn":"2020-03-20T00:00:00",
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "ExteriorPhotos",
               "RoomsPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2020-03-17T20:02:01.610487+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/1510-1687-fdb8c41de5f16515",
            "detailBasic":{
               "unitType":"None",
               "unitLevel":"Ground Level",
               "floors":1
            },
            "address":{
               "addressId":"da473a5e5c972acc",
               "streetAddress":"1388 Broadway",
               "city":"Millbrae",
               "zipcode":"94030",
               "state":"CA",
               "unitNumber":"185",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.4007432",
                  "longitude":"37.6087436"
               }
            },
            "unitNumber":"185",
            "areaInSquareFeet":1147,
            "bedroomCount":2,
            "fullBathroomCount":2,
            "halfBathroomCount":0
         },
         "address":{
            "addressId":"da473a5e5c972acc",
            "streetAddress":"1388 Broadway",
            "city":"Millbrae",
            "zipcode":"94030",
            "state":"CA",
            "unitNumber":"185",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.4007432",
               "longitude":"37.6087436"
            }
         },
         "listingInfo":{
            "depositAmount":3800.0000,
            "rentAmount":3800.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      },
      {
         "basicInfo":{
            "id":1677,
            "unitId":"5510755c859e808",
            "status":"InspectionScheduled",
            "isMediaReady":true,
            "isPublished":true,
            "isInspectionCompleted":false,
            "publishedOn":"2020-03-28T12:49:33.0240212+00:00",
            "onboardingInfo":{
               "existingResidents":[

               ]
            },
            "mediaAvailable":[
               "RoomsPhotos",
               "ExteriorPhotos",
               "Matterport",
               "Map",
               "StreetView",
               "GuidedTour"
            ],
            "managedSince":"2020-03-14T20:49:57.5464194+00:00",
            "bannerImageUrl":"https://s3-us-west-1.amazonaws.com/bln-prd-home-media/1500-1677-2a405db162b4e318",
            "detailBasic":{

            },
            "address":{
               "addressId":"947cd3a1c71e02c3",
               "streetAddress":"1425 Sandpiper Spit",
               "city":"Richmond",
               "zipcode":"94801",
               "state":"CA",
               "outsideUS":false,
               "coordinates":{
                  "latitude":"-122.3785605",
                  "longitude":"37.9076141"
               }
            },
            "unitNumber":"",
            "areaInSquareFeet":4929,
            "bedroomCount":4,
            "fullBathroomCount":4,
            "halfBathroomCount":1,
            "yearBuilt":2007,
            "zillowListingId":"1xn4hbmmefdr6_Postlets"
         },
         "address":{
            "addressId":"947cd3a1c71e02c3",
            "streetAddress":"1425 Sandpiper Spit",
            "city":"Richmond",
            "zipcode":"94801",
            "state":"CA",
            "outsideUS":false,
            "coordinates":{
               "latitude":"-122.3785605",
               "longitude":"37.9076141"
            }
         },
         "listingInfo":{
            "depositAmount":7050.0000,
            "rentAmount":7050.0000,
            "leaseMonths":12
         },
         "isDemoUnit":false,
         "isAvailableForRent":true
      }
   ]
}
 storedPosts = [];

 onPostadded(storedPosts){
   this.storedPosts.push(storedPosts);
 }


}
